config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'pages#index'
  resources :chats
  resources :messages
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat.rb
class Chat < ApplicationRecord
  has_many :messages
  belongs_to :user
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :chat
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :chats
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  before_action :authenticate_user!
  def index
    @chats = Chat.where(sender: current_user.username).or(Chat.where(receiver: current_user.username))
  end

  def new
    @chat = current_user.chats.build
  end

  def create
    @chat = current_user.chats.build(chat_params)
    if User.find_by(username: params[:chat][:receiver])
      if @chat.save
        redirect_to @chat
      else
        render 'new'
      end
    else
      @chaterror = 'Can\'t find receiver'
      render 'new'
    end
  end

  def show
    @chat = Chat.find(params[:id])
    @message = Message.new
  end

  private

  def chat_params
    params.require(:chat).permit(:sender, :receiver)
  end

  def find_chat
    @chat = Chat.find(params[:id])
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def new
    @message = Chat.find(message_params[:chat_id]).messages.build
  end

  def create
    @message = Chat.find(message_params[:chat_id]).messages.build(message_params)
    if @message.save
      redirect_to Chat.find(@message.chat_id)
    end
  end

  private

  def message_params
    params.require(:message).permit(:text, :author, :chat_id)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    render 'index'
  end
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  def new
    super
  end

  # POST /resource
  def create
    super
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:role, :username, :email, :password, :password_confirmation])
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/chats/index.html.erb
<div class="container">

  <div class="row">
    <div class="col-lg-12 text-center">
      <% @chats.each do |c| %>
        <div>
          <h3>From: <%= c.sender %></h3>
          <h3>To: <%= c.receiver %></h3>
          <%= link_to "Chat", c %>
        </div>
        <hr>
      <% end %>
    </div>
  </div>

</div>

app/views/chats/new.html.erb
<div class="container">

  <div class="row">
    <div class="col-lg-12 text-center">
      <h2>Sign up</h2>

<%= form_for @chat, url: {action: "create"} do |f| %>
  
  <div class="field">
    <%= f.label :sender %><br />
    <%= f.select :sender, options_for_select([['Myself', current_user.username]]) %>
  </div>

  <div class="field">
    <%= f.label :receiver %><br />
    <%= f.text_field :receiver, autofocus: true %>
  </div>

  <div class="actions">
    <%= f.submit "Create Chat" %>
  </div>
  <p class="error" style="color: red"><%= @chaterror %></p>
<% end %>
    </div>
  </div>

</div>

app/views/chats/show.html.erb
        <link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">

<div class="container">
        <div class="message-wrap col-lg-8">
            <div class="msg-wrap">
                <div class="media msg">
                <% @chat.messages.each do |m| %>
                <div class="media msg">

                    <div class="media-body">
                        <small class="pull-right time"><i class="fa fa-clock-o"></i> <%= m.created_at %></small>
                        <h5 class="media-heading"><%= m.author %></h5>

                        <small class="col-lg-10"><%= m.text %></small>
                    </div>
                </div>
                <% end %>

            </div>

            <div class="send-wrap ">
              <%= form_for @message, url: url_for(controller: 'messages', action: 'create') do |f| %>
                  <div class="field">
                    <%= f.text_field :text, autofocus: true, class: "form-control send-message", placeholder: "Write a reply...", rows: "3" %>
                  </div>
            <%= f.hidden_field :chat_id, value: @chat.id %>
            <%= f.hidden_field :author, value: current_user.username %>
            </div>
            <div class="btn-panel">
                  <div class="actions">
                    <%= f.submit "Send", class: "col-lg-4 text-right btn send-message-btn pull-right", role: "button"%>
                  </div>
            </div>
            <% end %>
        </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Chatstrew</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= render "shared/header" %>
    <%= yield %>
  </body>
</html>

app/views/pages/index.html.erb
<div class="container">

  <div class="row">
    <div class="col-lg-12 text-center">
      <h1>Welcome to ChatStrew</h1>
      <p class="lead">You can use ChatStrew to chat with trainers or users all around the world.</p>
      <a href="/chats/new"><button type="button" class="btn btn-default chat-button">New Chat</button></a>
    </div>
  </div>

</div>

app/views/shared/_header.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
      <a class="navbar-brand" href="#">ChatStrew</a>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li>
          <%= link_to "Home", root_url %>
        </li>
        <li>
          <% if user_signed_in? %>
            <%= link_to "Chats", chats_url %>
          <% else %>
            <%= link_to "Sign In", new_user_session_url %>
          <% end %>
        </li>
        <li>
          <% if user_signed_in? %>
            <%= link_to "Sign Out", destroy_user_session_path, :method => :delete %>
          <% else %>
            <%= link_to "Sign Up", new_user_registration_url %>
          <% end %>
        </li>
      </ul>
    </div>
    <!-- /.navbar-collapse -->
  </div>
  <!-- /.container -->
</nav>